import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

export default function PrivacyPolicy() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1">
        <div className="container mx-auto px-4 py-12 max-w-4xl">
          <h1 className="text-4xl font-bold tracking-tight mb-8">Privacy Policy</h1>
          <p className="text-muted-foreground mb-8">Last Updated: January 8, 2026</p>

          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
              <p className="text-foreground/90 leading-relaxed">
                Welcome to <strong>Bananaimage</strong>. We are committed to protecting your personal information and your right to privacy. This Privacy Policy explains how we collect, use, and share your information when you use our AI-powered image generation services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">2. Information We Collect</h2>
              <p className="text-foreground/90 mb-4">We collect information that you provide to us directly:</p>
              <ul className="list-disc pl-6 space-y-2 text-foreground/90">
                <li><strong>Account Information:</strong> Email address, username, and password.</li>
                <li><strong>User Content:</strong> Text prompts, negative prompts, and images you upload for image-to-image generation.</li>
                <li><strong>Generated Content:</strong> The images generated by our service based on your inputs.</li>
                <li><strong>Payment Information:</strong> We use third-party payment processors (e.g., Creem). We do not store your credit card details on our servers.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">3. How We Use Your Information</h2>
              <p className="text-foreground/90 mb-4">We use your information to:</p>
              <ul className="list-disc pl-6 space-y-2 text-foreground/90">
                <li>Provide, operate, and maintain our AI generation tools.</li>
                <li><strong>Process AI Generations:</strong> To generate images, your text prompts and uploaded images are processed by our system and may be transmitted to third-party AI model providers (such as Stable Diffusion, Midjourney, or other API partners) strictly for the purpose of content generation.</li>
                <li>Improve our services and fix bugs.</li>
                <li>Send you administrative information, such as updates to terms or policy changes.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">4. Sharing Information with Third Parties</h2>
              <p className="text-foreground/90 mb-4">
                We do not sell your personal data. However, due to the nature of our "AI Router" service, we must share specific data to function:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-foreground/90">
                <li><strong>AI Model Providers:</strong> Your prompts and input images are sent to external AI models to generate the final output. These providers are not authorized to use your personal data for other purposes.</li>
                <li><strong>Service Providers:</strong> We may use hosting services (e.g., AWS, Cloudflare) and payment processors (e.g., Creem) to run our business.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">5. Data Retention</h2>
              <p className="text-foreground/90 leading-relaxed">
                We retain your generated images and prompts for a limited period to allow you to access your history. You may delete your generated content at any time through your user dashboard.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">6. Contact Us</h2>
              <p className="text-foreground/90 leading-relaxed">
                If you have questions about this policy, please contact us at:
                <br />
                <strong>Email:</strong> support@bananaimage.online
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
